version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Location of your requirements.txt or pyproject.toml
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"  # Always use root for GitHub Actions
    schedule:
      interval: "weekly"
